openapi: "3.0.0"
info:
  title: Greeting Service
  version: 1.0.0
paths:
  /greeter/world:
    get:
      summary: Greet the world
      description: Say hello to the whole world!
      tags:
        - greeting
      parameters:
        - name: name
          in: query
          description: Name of the person to greet
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      deprecated: false
      security: []
