apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  # +optional Incoming connection details for the component (AKA endpoints).
  inbound:
    # +required Unique name for the endpoint.
    # This name will be used when generating the managed API
    - name: greeter-name-service
      # +required Numeric port value that gets exposed via the endpoint
      port: 8080
      # +required Type of traffic that the endpoint is accepting.
      # Allowed values: REST, GraphQL, GRPC, TCP, UDP, WS.
      type: REST
      # +optional Network level visibility of the endpoint. Defaults to Public
      # Accepted values: Project|Organization|Public.
      networkVisibility: Public
      # +optional Context (base path) of the API that gets exposed via the endpoint.
      # This is mandatory if the endpoint type is set to REST, GraphQL or WS.
      context: /greeting
      # +optional The path to the schema definition file. Defaults to wildcard route if not specified.
      # This is only applicable to REST and WS endpoint types.
      # The path should be relative to the Docker context.
      schemaFilePath: openapi.yaml
  # +optional Outgoing connection details for the component.
  outbound:
    # +optional Defines the service references from the Internal Marketplace.
    serviceReferences:
      # +required Name of the service reference.
    - name: choreo:///apifirst/testprojectchira/testservice/803f0/v1/PUBLIC
      connectionConfig: 01ef879c-4855-1b8e-8920-31c7fa2aae8d
        # +required Environment variables injected to the component for connection configuration.
      env:
        # +required Key name of the connection configuration
        - from: ServiceURL
          # +required Environment variable injected to the container
          to: SERVICE_URL
        - from: ConsumerKey
          to: CONSUMER_KEY
        - from: ConsumerSecret
          to: CONSUMER_SECRET
        - from: TokenURL
          to: TOKEN_URL