openapi: 3.0.0
info:
  title: Greeter API
  description: This API provides a greeter service that accepts a name and returns a greeting message.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /greeter/greet:
    get:
      summary: Get greeting message
      description: Returns a greeting message based on the provided name.
      parameters:
        - name: name
          in: query
          required: true
          description: Name to greet
          schema:
            type: string
      responses:
        '200':
          description: Successfully returns a greeting message.
          content:
            application/json:
              schema:
                type: string
                example: "Hello, John!"
        '500':
          description: Error occurred while processing the request
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"
      security:
        - oauth2_client_credentials: []

components:
  securitySchemes:
    oauth2_client_credentials:
      type: oauth2
      description: OAuth2 client credentials flow
      flows:
        clientCredentials:
          tokenUrl: https://sts.preview-dv.choreo.dev/oauth2/token
          scopes: {}

  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message

