openapi: 3.0.0
info:
  title: Greeter API
  description: This API provides a greeter service that interacts with two different services, one with OAuth2 authentication.
  version: 1.2.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /greeter/greetGo:
    get:
      summary: Get a greeting message using OAuth2
      description: Makes an OAuth2 authenticated request to retrieve a greeting message from the Go-1 service.
      responses:
        '200':
          description: Successfully returns a greeting message.
          content:
            application/json:
              schema:
                type: string
                example: "Hello, chira :from multi!"
        '500':
          description: Error occurred while processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - oauth2_client_credentials: []

  /greeter/greetGo2:
    get:
      summary: Get a greeting message using plain request
      description: Makes a plain request to retrieve a greeting message from the Go-2 service.
      responses:
        '200':
          description: Successfully returns a greeting message.
          content:
            application/json:
              schema:
                type: string
                example: "Hello, chira :from multi-2!"
        '500':
          description: Error occurred while processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /greeter/greetGoProj:
    get:
      summary: Get a greeting message using plain request
      description: Makes a plain request to retrieve a greeting message from the Go-proj1 service.
      responses:
        '200':
          description: Successfully returns a greeting message.
          content:
            application/json:
              schema:
                type: string
                example: "Hello, chira :from proj!"
        '500':
          description: Error occurred while processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /greeter/greetGoProj2:
    get:
      summary: Get a greeting message using plain request
      description: Makes a plain request to retrieve a greeting message from the Go-proj2 service.
      responses:
        '200':
          description: Successfully returns a greeting message.
          content:
            application/json:
              schema:
                type: string
                example: "Hello, chira :from proj2!"
        '500':
          description: Error occurred while processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    oauth2_client_credentials:
      type: oauth2
      description: OAuth2 client credentials flow for the Go-1 service
      flows:
        clientCredentials:
          tokenUrl: https://sts.preview-dv.choreo.dev/oauth2/token
          scopes: {}

  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
      example:
        message: "Internal server error"
