openapi: 3.0.0
info:
  title: Greeter API
  description: This API provides a greeter service that interacts with two services using OAuth2 authentication.
  version: 1.1.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /greeter/greet:
    get:
      summary: Get greeting message from Service 1
      description: Makes an OAuth2 authenticated request to Service 1 to get a greeting message. The message includes a name parameter.
      responses:
        '200':
          description: Successfully returns a greeting message from Service 1.
          content:
            application/json:
              schema:
                type: string
                example: "Hello, John!"
        '500':
          description: Error occurred while processing the request
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"
      security:
        - oauth2_client_credentials: []

  /greeter/world:
    get:
      summary: Get greeting message from Service 2
      description: Makes an OAuth2 authenticated request to Service 2 to return a simple greeting message.
      responses:
        '200':
          description: Successfully returns a greeting message from Service 2.
          content:
            application/json:
              schema:
                type: string
                example: "Hello, world!"
        '500':
          description: Error occurred while processing the request
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"
      security:
        - oauth2_client_credentials: []

components:
  securitySchemes:
    oauth2_client_credentials:
      type: oauth2
      description: OAuth2 client credentials flow for both services
      flows:
        clientCredentials:
          tokenUrl: https://sts.preview-dv.choreo.dev/oauth2/token
          scopes: {}

  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
